// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4RkzARW7NqkoD0PW6P8AEWXTIS2nqArU',
    appId: '1:229068929951:web:1ad8bbb307147eef5f1baa',
    messagingSenderId: '229068929951',
    projectId: 'fir-examples-1f2df',
    authDomain: 'fir-examples-1f2df.firebaseapp.com',
    storageBucket: 'fir-examples-1f2df.appspot.com',
    measurementId: 'G-XBQB185HVH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZmCySne15JB5WjVsrGg9mXyWbH7Dt_0U',
    appId: '1:229068929951:android:d1cf873720f891d05f1baa',
    messagingSenderId: '229068929951',
    projectId: 'fir-examples-1f2df',
    storageBucket: 'fir-examples-1f2df.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRHY2SHN3xRoPIZEFouJM8dc96eir_2iE',
    appId: '1:229068929951:ios:eb1e12c9b248c7fe5f1baa',
    messagingSenderId: '229068929951',
    projectId: 'fir-examples-1f2df',
    storageBucket: 'fir-examples-1f2df.appspot.com',
    iosClientId: '229068929951-nb5npn9j7ck0vq7nmel5rpilr28mjl6u.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
